### PR TITLE
Changed flask.ext import to new way of importing

### PR DESCRIPTION
**Pull request by nicoekkart**
flask.ext.migrate was still being used, while it should be flask_migrate

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Thanks, looks like I missed that one. :)

Note that I have inserted the change in the proper place in the commit history, so I'm going to close the PR instead of merge it.

**Comment by nicoekkart** [comment]
Ok thanks. I was apparently still looking in a branch...

**Comment by miguelgrinberg** [comment]
@nicoekkart you were looking in the right place. I just put the fix in after I saw your PR. :)

Unfortunately I cannot merge PR in the way most other projects on GitHub do, since I have to keep the history synchronized with the tags referenced in the book. So when I get a PR I have to manually insert it in the right place in the history.

**Comment by nicoekkart** [comment]
@miguelgrinberg Yep, got that right after I posted the comment (which is why I deleted it...). Thanks for elaborating!

**Pull request closed without merging**
